//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHAS.PO.INFRA.CROSS.GLOBALIZING {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHAS.PO.INFRA.CROSS.GLOBALIZING.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário aceitar o campo {0}..
        /// </summary>
        public static string Global_Checkbox {
            get {
                return ResourceManager.GetString("Global_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não conferem..
        /// </summary>
        public static string Global_Compare {
            get {
                return ResourceManager.GetString("Global_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no formato inválido..
        /// </summary>
        public static string Global_Date {
            get {
                return ResourceManager.GetString("Global_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no formato inválido..
        /// </summary>
        public static string Global_Email_Validator {
            get {
                return ResourceManager.GetString("Global_Email_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} precisa ter no mínimo {2} caracteres e no máximo {1} caracteres..
        /// </summary>
        public static string Global_Lenght {
            get {
                return ResourceManager.GetString("Global_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} precisa ter {1} caracteres..
        /// </summary>
        public static string Global_Lenght_Equal {
            get {
                return ResourceManager.GetString("Global_Lenght_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} pode possuir no máximo {1} caracteres..
        /// </summary>
        public static string Global_MaxLenght {
            get {
                return ResourceManager.GetString("Global_MaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} tem que possuir no mínimo {1} caracteres..
        /// </summary>
        public static string Global_MinLenght {
            get {
                return ResourceManager.GetString("Global_MinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} é de preenchimento obrigatório..
        /// </summary>
        public static string Global_Required {
            get {
                return ResourceManager.GetString("Global_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops!.
        /// </summary>
        public static string Global_Validacao_Erro {
            get {
                return ResourceManager.GetString("Global_Validacao_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrado!.
        /// </summary>
        public static string Global_Validacao_Sucesso {
            get {
                return ResourceManager.GetString("Global_Validacao_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feriado alterado com sucesso..
        /// </summary>
        public static string Validacao_Feriado_Editar_Sucesso {
            get {
                return ResourceManager.GetString("Validacao_Feriado_Editar_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feriado criado com sucesso..
        /// </summary>
        public static string Validacao_Feriado_Novo_Sucesso {
            get {
                return ResourceManager.GetString("Validacao_Feriado_Novo_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data escolhida para o feriado já existe e não há necessidade de cadastrar novamente..
        /// </summary>
        public static string Validacao_Feriado_Repetido {
            get {
                return ResourceManager.GetString("Validacao_Feriado_Repetido", resourceCulture);
            }
        }
    }
}
